apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: ingress-nginx
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: aHlwZXJ2aXNvckAyMDAx # Base64-encoded value of the MySQL root password
  MYSQL_USER: aHlwZXJ2aXNpb24= # Base64-encoded value of the MySQL user name
  MYSQL_PASSWORD: aHlwZXJ2aXNvckAyMDAx # Base64-encoded value of the MySQL password
  MYSQL_DATABASE: ZGhhbnVzaGRi # Base64-encoded value of the MySQL database name
