apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-container
          image: your_nodejs_image:tag
          ports:
            - containerPort: 5000  

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: sql
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP



