apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: ingress-nginx
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-container
          image: hypervision201/kube-conc-backend:253
          imagePullPolicy: Always
          ports:
            - containerPort: 5000  
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: ingress-nginx
  labels:
    app: nodejs-app
spec:
  clusterIP: None
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: node-service1
#   namespace: ingress-nginx
#   labels:
#     app: nodejs-app
# spec:
#   selector:
#     app: nodejs-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#   type: LoadBalancer



